"""Projection behavior the bundled corpus cannot exercise (DO-013A Stage A).

Every bundled lesson is 480 PPQ, single-meter, exact quarter notes, gapless. So
the corpus can never show what happens at a meter change, across real silence,
on a duration the grammar cannot spell, or where an engraver would expect a tie.
Five constructed revisions cover exactly those gaps.

The fixtures are generated by ``scripts/build_projection_fixtures.py`` running
the production builders; these tests assert what the generated files actually
say. Two different failures are therefore possible and both matter: the file
drifting from its generator, and the generator producing something that no longer
matches the claim its case was written to prove.
"""

from __future__ import annotations

import functools
import importlib.util
import json
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
EXAMPLES = REPO_ROOT / "resources" / "projections" / "examples"
GENERATOR = REPO_ROOT / "scripts" / "build_projection_fixtures.py"

NOTATION_CASES = [
    "meter_change_notation",
    "global_rest_notation",
    "unsupported_duration_notation",
    "unsupported_tie_notation",
]
ALL_CASES = ["unresolved_tab", *NOTATION_CASES]


@functools.lru_cache(maxsize=1)
def _generator():
    """Load the fixture generator as a module.

    By path rather than as ``scripts.build_projection_fixtures``: ``scripts/`` is
    not a package and is only importable when the repository root happens to be on
    ``sys.path``, which is true under ``python -m pytest`` and false under the
    bare ``pytest`` CI runs.

    Registered in ``sys.modules`` before execution because the generator defines a
    dataclass, and ``dataclasses`` resolves a field's annotations by looking its
    defining module up there. A module executed without being registered has no
    entry to find, so the class body raises before the module finishes loading.
    """

    name = "build_projection_fixtures"
    spec = importlib.util.spec_from_file_location(name, GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _load(name: str) -> dict:
    return json.loads((EXAMPLES / f"{name}.json").read_text(encoding="utf-8"))


def _notes(projection: dict) -> list[dict]:
    return [
        event
        for measure in projection["measures"]
        for event in measure["events"]
        if event["event_kind"] == "note"
    ]


def _rests(projection: dict) -> list[dict]:
    return [
        event
        for measure in projection["measures"]
        for event in measure["events"]
        if event["event_kind"] == "rest"
    ]


def _codes(projection: dict) -> list[str]:
    return [item["code"] for item in projection["unsupported_features"]]


# --- the files match their generator -----------------------------------------


@pytest.mark.parametrize("name", ALL_CASES)
def test_every_case_is_checked_in(name: str) -> None:
    assert (EXAMPLES / f"{name}.json").exists()


def test_the_fixtures_are_regenerable_and_current() -> None:
    """The files claim to be generated; prove the generator still produces them."""

    assert _generator().main(["--check"]) == 0


def test_the_drift_check_rejects_a_tampered_fixture(tmp_path: Path) -> None:
    """A checker that accepts everything would make the guard above meaningless."""

    module = _generator()
    case = module.UNRESOLVED_TAB
    original = module.fixture_path(case).read_text(encoding="utf-8")
    tampered = json.loads(original)
    tampered["events"][1]["status"] = "playable"
    module.fixture_path(case).write_text(
        json.dumps(tampered, indent=2) + "\n", encoding="utf-8"
    )
    try:
        assert module.main(["--check"]) == 1
    finally:
        module.fixture_path(case).write_text(original, encoding="utf-8")


def test_no_untracked_fixtures() -> None:
    """The directory is the case list, so an orphan file cannot hide in it."""

    assert {path.stem for path in EXAMPLES.glob("*.json")} == set(ALL_CASES)


# --- fixtures come from production, not from hand-written JSON ---------------


def test_every_case_runs_through_a_production_builder() -> None:
    """The whole point: unusual input, production answers."""

    import inspect

    source = inspect.getsource(_generator().render_case)
    assert "build_tab_projection" in source
    assert "build_notation_projection" in source


@pytest.mark.parametrize("name", ALL_CASES)
def test_each_projection_cites_its_own_revision(name: str) -> None:
    projection = _load(name)
    assert projection["canonical_revision_id"].startswith("rev-")


def test_the_cases_have_distinct_revisions() -> None:
    """Five different pieces of music must not share one identity."""

    ids = {_load(name)["canonical_revision_id"] for name in ALL_CASES}
    assert len(ids) == len(ALL_CASES)


def test_synthetic_revisions_never_impersonate_a_lesson() -> None:
    """Provenance and timestamp both mark these as constructed, not authored."""

    module = _generator()
    from master_all_strings.lesson.canonicalization import AUTHORED_LESSON_POLICY_VERSION

    assert module.SYNTHETIC_FIXTURE_POLICY_VERSION != AUTHORED_LESSON_POLICY_VERSION
    revision = module.build_synthetic_revision(module.UNRESOLVED_TAB)
    assert revision.provenance.policy_version == module.SYNTHETIC_FIXTURE_POLICY_VERSION
    assert revision.created_at == module.SYNTHETIC_FIXTURE_CREATED_AT_UTC


def test_synthetic_revisions_are_deterministic() -> None:
    module = _generator()
    first = module.build_synthetic_revision(module.GLOBAL_REST_NOTATION)
    second = module.build_synthetic_revision(module.GLOBAL_REST_NOTATION)
    assert first.revision_id == second.revision_id
    assert first.content_digest == second.content_digest


# --- unresolved_tab ----------------------------------------------------------


def test_withheld_spatial_evidence_yields_unresolved() -> None:
    projection = _load("unresolved_tab")
    unresolved = [e for e in projection["events"] if e["status"] == "unresolved"]
    assert [e["canonical_event_id"] for e in unresolved] == ["ev-2"]


def test_an_unresolved_event_carries_no_string_or_fret() -> None:
    """The failure mode this case exists for: TAB filling in a plausible guess."""

    projection = _load("unresolved_tab")
    event = next(e for e in projection["events"] if e["status"] == "unresolved")
    assert event["string_id"] is None
    assert event["fret"] is None


def test_the_control_event_is_still_playable() -> None:
    """Same builder, same call, evidence present -- so the difference is evidence."""

    projection = _load("unresolved_tab")
    event = next(e for e in projection["events"] if e["canonical_event_id"] == "ev-1")
    assert event["status"] == "playable"
    assert event["string_id"] is not None
    assert event["fret"] is not None


def test_an_unresolved_event_keeps_its_canonical_music() -> None:
    """Unresolved is a statement about fingering, not about the note."""

    projection = _load("unresolved_tab")
    event = next(e for e in projection["events"] if e["canonical_event_id"] == "ev-2")
    assert event["midi_note"] == 65
    assert event["start_tick"] == 480
    assert event["duration_ticks"] == 480


# --- meter_change_notation ---------------------------------------------------


def test_a_meter_change_produces_measures_of_the_right_lengths() -> None:
    measures = _load("meter_change_notation")["measures"]
    assert [(m["start_tick"], m["end_tick"]) for m in measures] == [(0, 1920), (1920, 3360)]


def test_each_measure_reports_the_meter_in_force() -> None:
    measures = _load("meter_change_notation")["measures"]
    assert [(m["meter"]["numerator"], m["meter"]["denominator"]) for m in measures] == [
        (4, 4),
        (3, 4),
    ]


def test_notes_land_in_the_measure_that_contains_them() -> None:
    """A builder that cached the opening meter would misplace the 3/4 notes."""

    measures = _load("meter_change_notation")["measures"]
    assert [len(m["events"]) for m in measures] == [4, 3]
    for measure in measures:
        for event in measure["events"]:
            assert measure["start_tick"] <= event["start_tick"] < measure["end_tick"]


def test_a_meter_change_invents_no_rests() -> None:
    assert _rests(_load("meter_change_notation")) == []


# --- global_rest_notation ----------------------------------------------------


def test_exactly_one_rest_is_derived_for_the_one_real_silence() -> None:
    rests = _rests(_load("global_rest_notation"))
    assert len(rests) == 1
    assert (rests[0]["start_tick"], rests[0]["duration_ticks"]) == (480, 240)


def test_the_derived_rest_is_spelled_and_labeled() -> None:
    rest = _rests(_load("global_rest_notation"))[0]
    assert rest["display_duration"] == "eighth"
    assert rest["derivation"] == "global_silence"
    assert rest["canonical_event_id"] is None


def test_no_rest_overlaps_a_sounding_note() -> None:
    """The invariant the whole global-silence rule exists to protect."""

    projection = _load("global_rest_notation")
    for rest in _rests(projection):
        rest_end = rest["start_tick"] + rest["duration_ticks"]
        for note in _notes(projection):
            note_end = note["start_tick"] + note["duration_ticks"]
            assert rest["start_tick"] >= note_end or rest_end <= note["start_tick"]


def test_the_notes_survive_the_gap_unchanged() -> None:
    notes = _notes(_load("global_rest_notation"))
    assert [(n["start_tick"], n["duration_ticks"]) for n in notes] == [(0, 480), (720, 240)]


# --- unsupported_duration_notation -------------------------------------------


def test_an_unspellable_duration_is_reported() -> None:
    assert "unsupported_display_duration" in _codes(_load("unsupported_duration_notation"))


def test_an_unspellable_duration_is_not_rounded() -> None:
    """45 ticks stays 45 ticks, with no display duration invented for it."""

    note = _notes(_load("unsupported_duration_notation"))[0]
    assert note["duration_ticks"] == 45
    assert note["display_duration"] is None


def test_unsupported_ness_propagates_to_a_derived_rest() -> None:
    """The builder computed 435 ticks itself and must not smooth its own output."""

    rest = _rests(_load("unsupported_duration_notation"))[0]
    assert rest["duration_ticks"] == 435
    assert rest["display_duration"] is None


def test_the_unsupported_report_names_the_offending_event() -> None:
    features = _load("unsupported_duration_notation")["unsupported_features"]
    assert any(item["canonical_event_id"] == "ev-1" for item in features)


def test_a_spellable_neighbour_is_unaffected() -> None:
    """One bad duration must not disqualify the rest of the measure."""

    note = _notes(_load("unsupported_duration_notation"))[-1]
    assert note["display_duration"] == "quarter"


# --- unsupported_tie_notation ------------------------------------------------


def test_adjacent_same_pitch_notes_stay_two_events() -> None:
    notes = _notes(_load("unsupported_tie_notation"))
    assert len(notes) == 2
    assert notes[0]["midi_note"] == notes[1]["midi_note"]
    assert notes[0]["canonical_event_id"] != notes[1]["canonical_event_id"]


def test_the_two_notes_meet_exactly_at_the_barline() -> None:
    """The textbook shape an engraver ties -- so the negative result is meaningful."""

    notes = _notes(_load("unsupported_tie_notation"))
    assert notes[0]["start_tick"] + notes[0]["duration_ticks"] == notes[1]["start_tick"]
    measures = _load("unsupported_tie_notation")["measures"]
    assert notes[0]["start_tick"] < measures[1]["start_tick"] <= notes[1]["start_tick"]


def test_no_tie_is_reported_as_an_unsupported_feature() -> None:
    """Ties are not inferred, so there is no tie to report as unsupported either."""

    assert _codes(_load("unsupported_tie_notation")) == []


def test_no_tie_metadata_appears_anywhere_in_the_payload() -> None:
    """Broad on purpose: catches a tie field added under any name or nesting."""

    assert "tie" not in json.dumps(_load("unsupported_tie_notation")).lower()


def test_both_notes_keep_their_own_display_duration() -> None:
    notes = _notes(_load("unsupported_tie_notation"))
    assert [n["display_duration"] for n in notes] == ["whole", "whole"]
