"""Regenerate the cross-language interpolation vectors (DO-012).

`resources/presentation/examples/interpolation_vectors.json` is the contract
between `master_all_strings.presentation.timeline` and the browser's mirror in
`web/mvp1/teaching-timeline.js`. It claims to be generated; this is the
generator, so the claim is checkable and the golden case cannot drift away from
the lesson it names.

The two synthetic cases are declared here as tempo maps rather than as literal
numbers: every anchor and probe is computed through Musical Core, so a change in
Core's mapping shows up as a diff in this file instead of silently disagreeing
with it. The golden case is derived from the demo library, so its tick domain is
whatever the lesson actually exports -- never a hand-typed guess.

Usage: python scripts/build_interpolation_vectors.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from master_all_strings.core.score.tempo import TempoChangeV1
from master_all_strings.mvp.application import MvpApplication
from master_all_strings.mvp.demo_library import load_demo_manifest
from master_all_strings.presentation.contracts import PRESENTATION_SCHEMA_VERSION
from master_all_strings.presentation.timeline import (
    build_timeline_anchors,
    seconds_to_tick_from_anchors,
    tick_to_seconds_from_anchors,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
VECTORS = REPO_ROOT / "resources" / "presentation" / "examples" / "interpolation_vectors.json"

GOLDEN_DEMO_ID = "half_steps_one_string"

DESCRIPTION = (
    "Cross-language interpolation vectors. Generated by "
    "scripts/build_interpolation_vectors.py from "
    "master_all_strings.presentation.timeline; consumed by both the Python and "
    "Node test suites so the browser's interpolation cannot silently diverge "
    "from Musical Core's mapping."
)


def _tempo(tick: int, microseconds_per_quarter: int) -> TempoChangeV1:
    return TempoChangeV1(
        schema_version=TempoChangeV1.SCHEMA_VERSION,
        tick=tick,
        microseconds_per_quarter=microseconds_per_quarter,
    )


def _case(
    *,
    case_id: str,
    description: str,
    ticks_per_quarter: int,
    tempo_changes: tuple[TempoChangeV1, ...],
    total_ticks: int,
    tick_probes: tuple[int, ...],
    seconds_probes: tuple[float, ...],
) -> dict[str, Any]:
    anchors = build_timeline_anchors(
        ticks_per_quarter=ticks_per_quarter,
        tempo_changes=tempo_changes,
        total_ticks=total_ticks,
    )
    return {
        "case_id": case_id,
        "description": description,
        # Recorded so a reader can tell which tick domain the case lives in.
        # The browser never needs these; a human comparing cases very much does.
        "ticks_per_quarter": ticks_per_quarter,
        "total_ticks": total_ticks,
        "anchors": [
            {
                "schema_version": anchor.schema_version,
                "tick": anchor.tick,
                "seconds": anchor.seconds,
            }
            for anchor in anchors
        ],
        "tick_to_seconds_from_anchors": [
            {"tick": tick, "seconds": tick_to_seconds_from_anchors(anchors, tick)}
            for tick in tick_probes
        ],
        "seconds_to_tick_from_anchors": [
            {"seconds": seconds, "tick": seconds_to_tick_from_anchors(anchors, seconds)}
            for seconds in seconds_probes
        ],
    }


def _golden_case() -> dict[str, Any]:
    """Derive the golden case from the lesson itself, not from memory."""

    entry = next(e for e in load_demo_manifest() if e.demo_id == GOLDEN_DEMO_ID)
    response = MvpApplication().run_demo(
        entry.demo_id, instrument_profile_id=entry.instrument_profile_id
    )
    projection = response.projection
    timeline = projection.timeline
    tempo_changes = tuple(
        _tempo(change.tick, change.microseconds_per_quarter)
        for change in projection.tempo_changes
    )
    # Probe every note onset plus the endpoints: those are the positions the
    # playhead actually has to resolve during the lesson.
    onsets = tuple(note.onset_tick for note in projection.notes)
    tick_probes = tuple(sorted({0, *onsets, timeline.total_ticks}))
    seconds_probes = tuple(
        tick_to_seconds_from_anchors(
            build_timeline_anchors(
                ticks_per_quarter=timeline.ticks_per_quarter,
                tempo_changes=tempo_changes,
                total_ticks=timeline.total_ticks,
            ),
            tick,
        )
        for tick in tick_probes
    )
    return _case(
        case_id=GOLDEN_DEMO_ID,
        description=(
            "The golden lesson, derived from the demo library: "
            f"{timeline.total_ticks} ticks at {timeline.ticks_per_quarter} PPQ "
            f"spanning {timeline.total_seconds}s."
        ),
        ticks_per_quarter=timeline.ticks_per_quarter,
        tempo_changes=tempo_changes,
        total_ticks=timeline.total_ticks,
        tick_probes=tick_probes,
        seconds_probes=seconds_probes,
    )


def build() -> dict[str, Any]:
    constant = _case(
        case_id="constant_120bpm",
        description="Single tempo; anchors are just the endpoints.",
        ticks_per_quarter=960,
        tempo_changes=(_tempo(0, 500_000),),
        total_ticks=8640,
        # Includes a probe past the last anchor: extrapolation at the final rate
        # is part of the contract, not an accident of the implementation.
        tick_probes=(0, 1, 480, 960, 2880, 4320, 8640, 17280),
        seconds_probes=(0.0, 0.25, 0.5, 1.5, 2.25, 4.5, 9.0),
    )
    tempo_change = _case(
        case_id="tempo_change_120_to_90",
        description="Tempo change at tick 1920 becomes an interior anchor.",
        ticks_per_quarter=960,
        tempo_changes=(_tempo(0, 500_000), _tempo(1920, 666_667)),
        total_ticks=8640,
        # Straddles the boundary tick by one in each direction: an off-by-one in
        # segment selection is invisible at the boundary itself.
        tick_probes=(0, 960, 1919, 1920, 1921, 3840, 8640, 12000),
        seconds_probes=(0.0, 0.5, 1.0, 2.0, 3.5, 5.666669),
    )
    return {
        "schema_version": PRESENTATION_SCHEMA_VERSION,
        "description": DESCRIPTION,
        "cases": [constant, tempo_change, _golden_case()],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the file is stale",
    )
    args = parser.parse_args(argv)

    rendered = json.dumps(build(), indent=2) + "\n"
    if args.check:
        current = VECTORS.read_text(encoding="utf-8") if VECTORS.exists() else ""
        if current != rendered:
            print(
                f"{VECTORS} is stale; run python scripts/build_interpolation_vectors.py",
                file=sys.stderr,
            )
            return 1
        return 0

    VECTORS.write_text(rendered, encoding="utf-8")
    print(f"wrote {VECTORS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
